### ISSUE TITLE
Unable to make protected void java.util.ResourceBundle.setParent(java.util.ResourceBundle) accessible: module java.base does not "opens java.util" to 

### ISSUE THREAD

**Issue by al1020119** [oldmanpushcart/dashscope4j#3]
Internal error (java.lang.reflect.InaccessibleObjectException): Unable to make protected void java.util.ResourceBundle.setParent(java.util.ResourceBundle) accessible: module java.base does not "opens java.util" to unnamed module @55a561cf
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.util.ResourceBundle.setParent(java.util.ResourceBundle) accessible: module java.base does not "opens java.util" to unnamed module @55a561cf
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.intellij.util.ReflectionUtil.makeAccessible(ReflectionUtil.java:253)
	at com.intellij.util.ReflectionUtil.getDeclaredMethod(ReflectionUtil.java:270)
	at com.intellij.DynamicBundle.<clinit>(DynamicBundle.java:28)
	at org.jetbrains.jps.incremental.scala.ScalaCompilerReferenceIndexBuilder.getPresentableName(ScalaCompilerReferenceIndexBuilder.scala:23)
	at org.jetbrains.jps.incremental.IncProjectBuilder.lambda$sendElapsedTimeMessages$3(IncProjectBuilder.java:451)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3652)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.jetbrains.jps.incremental.IncProjectBuilder.sendElapsedTimeMessages(IncProjectBuilder.java:454)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:425)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:183)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:132)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:219)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by oldmanpushcart** [comment]
请问这个是什么场景下出现的？能告知我复现的步骤么？

从异常堆栈的上下文来看，更像是你自己的代码中没有考虑到java9新引入的modular的特性？只是个建议，仅供参考。

**Comment by al1020119** [comment]
开始下载启动提示版本问题：
错误的类文件: /Users/edy/Service/Mavens/apache-maven-3.8.4/repository/io/github/oldmanpushcart/dashscope4j/1.2.1/dashscope4j-1.2.1.jar!/io/github/oldmanpushcart/dashscope4j/DashScopeClient.class
类文件具有错误的版本 61.0, 应为 52.0
请删除该文件或确保该文件位于正确的类路径子目录中。

后面本地改成17后，直接报这个错误
![image](https://github.com/oldmanpushcart/dashscope4j/assets/9606161/a40e5597-dc64-40d4-9194-cffbf5f05991)
![image](https://github.com/oldmanpushcart/dashscope4j/assets/9606161/c1c2af2b-b9d7-4a8b-a998-97e3db5d4a35)

**Comment by oldmanpushcart** [comment]
### 关于“类文件具有错误的版本 61.0, 应为 52.0”

这个是要求JDK17。61.0对应JDK17，52.0对应JDK8

### 关于异常堆栈

#### 问题原因分析
异常堆栈表明你的IDEA中某个与scala相关的插件不支持JDK9+的版本，
   
这个错误信息表明，在 IntelliJ IDEA 或其相关的 JetBrains 开发环境中，由于 Java 模块系统（Jigsaw Project Jigsaw）的安全性和封装性增强，在某个插件尝试访问 java.util.ResourceBundle 类的受保护方法 setParent 时遇到了访问限制。具体来说，Java 模块 java.base 没有显式地向匿名模块（unnamed module）开放 java.util 包，因此不能通过反射的方式访问 ResourceBundle 的内部方法。

从堆栈跟踪可以看出，这个错误是在处理 Scala 编译相关任务时发生的，涉及到了 IntelliJ IDEA 内部的 com.intellij.util.ReflectionUtil 类，以及 org.jetbrains.jps.incremental.scala.ScalaCompilerReferenceIndexBuilder 类，这通常与 Scala 插件或者与 Scala 和 Maven/Gradle 构建工具集成的插件有关。

解决此类问题的方法通常是更新或配置相关插件，使其遵循 Java 模块系统的规则。如果插件本身存在不兼容 Java 模块化特性的代码，可能需要等待插件开发者修复并发布新版本。另外，也可以尝试调整 IntelliJ IDEA 中的模块化配置或者启动参数，以允许对特定内部API的访问。

#### 临时规避方案

在相关的功能的启动参数上增加JVM参数`--add-opens java.base/java.util=ALL-UNNAMED`，从堆栈上下文来看，应该是在你的构建参数中增加。

#### 长期规避方案

升级你的scala插件，说不定新版本的插件已经解决了这个问题。毕竟JDK9都出来那么久了。
